require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe WordsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Word. As you add validations to Word, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {spelling: 'clam'}
  }

  let(:invalid_attributes) {
    {spelling: ''}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Word.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      word = Word.create! valid_attributes
      get :show, params: {id: word.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      word = Word.create! valid_attributes
      get :edit, params: {id: word.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Word" do
        expect {
          post :create, params: {word: valid_attributes}, session: valid_session
        }.to change(Word, :count).by(1)
      end

      it "redirects to the created word" do
        post :create, params: {word: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Word.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {word: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {spelling: 'oyster'}
      }

      it "updates the requested word" do
        word = Word.create! valid_attributes
        put :update, params: {id: word.to_param, word: new_attributes}, session: valid_session
        word.reload
        expect(word.spelling).to match('oyster')
      end

      it "redirects to the word" do
        word = Word.create! valid_attributes
        put :update, params: {id: word.to_param, word: valid_attributes}, session: valid_session
        expect(response).to redirect_to(word)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        word = Word.create! valid_attributes
        put :update, params: {id: word.to_param, word: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested word" do
      word = Word.create! valid_attributes
      expect {
        delete :destroy, params: {id: word.to_param}, session: valid_session
      }.to change(Word, :count).by(-1)
    end

    it "redirects to the words list" do
      word = Word.create! valid_attributes
      delete :destroy, params: {id: word.to_param}, session: valid_session
      expect(response).to redirect_to(words_url)
    end
  end

end
